// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdb8ckAPRsKafTRIZ71RiB7MxSXcWLGmk',
    appId: '1:707876329859:web:c6691aa471a02ddbb8feb6',
    messagingSenderId: '707876329859',
    projectId: 'ssh-project-7ebc3',
    authDomain: 'ssh-project-7ebc3.firebaseapp.com',
    databaseURL: 'https://ssh-project-7ebc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ssh-project-7ebc3.firebasestorage.app',
    measurementId: 'G-ZS5BQEPPMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpAjgTa4nGnS0P5kIfl8PC2LYhw5zYvQ8',
    appId: '1:707876329859:android:1a7f797f5626582ab8feb6',
    messagingSenderId: '707876329859',
    projectId: 'ssh-project-7ebc3',
    databaseURL: 'https://ssh-project-7ebc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ssh-project-7ebc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ESh7rtBAcD1axTuN88CBHADymgC57Vs',
    appId: '1:707876329859:ios:82bd5ef3d8c59459b8feb6',
    messagingSenderId: '707876329859',
    projectId: 'ssh-project-7ebc3',
    databaseURL: 'https://ssh-project-7ebc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ssh-project-7ebc3.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ESh7rtBAcD1axTuN88CBHADymgC57Vs',
    appId: '1:707876329859:ios:82bd5ef3d8c59459b8feb6',
    messagingSenderId: '707876329859',
    projectId: 'ssh-project-7ebc3',
    databaseURL: 'https://ssh-project-7ebc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ssh-project-7ebc3.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdb8ckAPRsKafTRIZ71RiB7MxSXcWLGmk',
    appId: '1:707876329859:web:8781f7c06c67b7e6b8feb6',
    messagingSenderId: '707876329859',
    projectId: 'ssh-project-7ebc3',
    authDomain: 'ssh-project-7ebc3.firebaseapp.com',
    databaseURL: 'https://ssh-project-7ebc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ssh-project-7ebc3.firebasestorage.app',
    measurementId: 'G-D2Z34ZZZ0Y',
  );

}