// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbVwSai9_0oOGJKStKeNogsDfG39CL50',
    appId: '1:977763811180:web:44031103fc2b099e77fd49',
    messagingSenderId: '977763811180',
    projectId: 'hackproj-190',
    authDomain: 'hackproj-190.firebaseapp.com',
    storageBucket: 'hackproj-190.firebasestorage.app',
    measurementId: 'G-T48WL00K9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaPzYC3LwXYkIERgo8YT8Zkz7Vm7ERD8U',
    appId: '1:977763811180:android:2f41ea271fe5b63e77fd49',
    messagingSenderId: '977763811180',
    projectId: 'hackproj-190',
    storageBucket: 'hackproj-190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbJk0LwgeuIAUZZiQnjZCbSYyE0tTP304',
    appId: '1:977763811180:ios:6648f0a9bd4a1cb177fd49',
    messagingSenderId: '977763811180',
    projectId: 'hackproj-190',
    storageBucket: 'hackproj-190.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbJk0LwgeuIAUZZiQnjZCbSYyE0tTP304',
    appId: '1:977763811180:ios:6648f0a9bd4a1cb177fd49',
    messagingSenderId: '977763811180',
    projectId: 'hackproj-190',
    storageBucket: 'hackproj-190.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbVwSai9_0oOGJKStKeNogsDfG39CL50',
    appId: '1:977763811180:web:4509188bab6745df77fd49',
    messagingSenderId: '977763811180',
    projectId: 'hackproj-190',
    authDomain: 'hackproj-190.firebaseapp.com',
    storageBucket: 'hackproj-190.firebasestorage.app',
    measurementId: 'G-KR2M846WWK',
  );
}
